---
title: "Diversos gráficos da distribuição lognormal no R"
author: "Luiz Fernando Palin Droubi"
date: "23/02/2018"
output:
  pdf_document: default
  html_document:
    keep_md: yes
    self_contained: no
header-includes:
  - \usepackage{animate}
---

Aprenda como plotar a distribuição lognormal de diversas formas, como esta:

```{r setup, echo = FALSE}
knitr::opts_chunk$set(fig.path = "images/", dev = "png", fig.align = "center",
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
library(ggplot2)
library(reshape2)
library(ggthemes)
library(latex2exp)
theme_set(theme_bw())
```

```{r lognormal, echo = FALSE, fig.show='animate', fig.width=5, fig.height=4, interval=.1}
x <- seq(0, 3, 0.05)
mediana <- 1
sigma <- seq(1.4, 0.1, -0.1)
for (s in sigma) {
  y <- dlnorm(x = x, meanlog = log(1), sdlog = s)
  data <- data.frame(x, y)
  media <- mediana*exp(s^2/2)
  moda <- mediana/exp(s^2)
  p <- ggplot(data, aes(x = x, y = y)) + geom_line() + 
    geom_segment(aes(x = media, y = 0, xend = media, 
                   yend = dlnorm(media, meanlog = log(mediana), sdlog = s),
                   colour = "Média")) +
    geom_segment(aes(x = mediana, y = 0, xend = mediana,
                   yend = dlnorm(mediana, meanlog = log(mediana), sdlog = s),
                   colour = "Mediana")) +
    geom_segment(aes(x = moda, y = 0, xend = moda, 
                   yend = dlnorm(moda, meanlog = log(mediana), sdlog = s),
                   colour = "Moda"))
  print(p)
}
```



